config/routes.rb
Rails.application.routes.draw do
  mount ActionImageUploader::UploadEndpoint, at: '/action_images'
  mount CategoryIconUploader::UploadEndpoint, at: '/category_icons'
  mount IssueIconUploader::UploadEndpoint, at: '/issue_icons'
  mount ProfileAvatarUploader::UploadEndpoint, at: '/profile_avatars'

  namespace :admin do
    resources :actions
    resources :categories
    resources :features
    resources :issues
    resources :users

    root to: 'dashboard#index'
  end

  resource :profile, only: [:edit, :show, :update]

  root to: 'pages#home'
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    include Clearance::Controller
    include ::Pundit

    layout 'admin'

    before_action :require_login
    before_action :authenticate_admin

    private

    def authenticate_admin
      redirect_to sign_in_url unless signed_in? && current_user.admin?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit

  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_navbar.html.slim
section.container.grid-960
  .columns
    .column
      header.navbar
        section.navbar-section
          a.navbar-brand href=admin_root_path
            = image_tag 'brand/reaction-logo-square-sm@2x.png', size: '32x32'
          a.btn.btn-link class="#{'active' if controller_name == 'issues'}" href=admin_issues_path Issues
          a.btn.btn-link class="#{'active' if controller_name == 'categories'}" href=admin_categories_path Categories
          a.btn.btn-link class="#{'active' if controller_name == 'actions'}" href=admin_actions_path Actions
          a.btn.btn-link class="#{'active' if controller_name == 'features'}" href=admin_features_path Features
          a.btn.btn-link class="#{'active' if controller_name == 'users'}" href=admin_users_path Users
        section.navbar-section
          - if signed_in?
            small
              ' Signed in as:
              = link_to current_user.email, profile_path
            figure.avatar.avatar-sm.ml-10.media-figure
              = image_tag current_user.profile.avatar_url, size: '24x24'
            = button_to t('.sign_out'), sign_out_path, method: :delete, class: 'btn btn-sm ml-10'
          - else
            = link_to t('.sign_in'), sign_in_path