config/routes.rb
Rails.application.routes.draw do
  mount ActionImageUploader::UploadEndpoint, at: '/action_images'
  mount CategoryIconUploader::UploadEndpoint, at: '/category_icons'
  mount IssueIconUploader::UploadEndpoint, at: '/issue_icons'
  mount ProfileAvatarUploader::UploadEndpoint, at: '/profile_avatars'

  namespace :admin do
    resources :actions
    resources :categories
    resources :features
    resources :issues
    resources :users

    root to: 'dashboard#index'
  end

  resource :profile, only: [:edit, :show, :update]

  root to: 'pages#home'
end

app/controllers/admin/actions_controller.rb
module Admin
  class ActionsController < Admin::ApplicationController
    before_action :set_action, only: [:show, :edit, :update, :destroy]
    after_action :verify_authorized

    def index
      @actions = Action.all
      authorize @actions
    end

    def show
      authorize @action
    end

    def new
      @action = Action.new
      authorize @action
    end

    def edit
      authorize @action
    end

    def create
      @action = Action.new(action_params)
      authorize @action

      if @action.save
        redirect_to(
          [:admin, @action], notice: 'Action was successfully created.'
        )
      else
        render :new
      end
    end

    def update
      authorize @action
      if @action.update(action_params)
        redirect_to(
          [:admin, @action], notice: 'Action was successfully updated.'
        )
      else
        render :edit
      end
    end

    def destroy
      authorize @action
      @action.destroy
      redirect_to(
        admin_actions_url, notice: 'Action was successfully removed.'
      )
    end

    private

    def set_action
      @action = Action.find(params[:id])
    end

    def action_params
      params.require(:action_item).permit(
        :body, :category_id, :event, :eyebrow, :happening_at, :image,
        :issue_id, :location, :priority, :summary, :remove_image,
        :time_commitment, :title
      )
    end
  end
end

app/helpers/admin/action_helper.rb
module Admin
  module ActionHelper
    def options_for_actions_category_select
      Category.order(name: :asc).all.map do |category|
        [
          category.name,
          category.id,
        ]
      end
    end

    def options_for_actions_priority_select
      Action.priorities.map do |priority|
        [
          I18n.t(
            priority.first,
            scope: 'activerecord.attributes.action.priorities',
          ),
          priority.first,
        ]
      end
    end

    def options_for_actions_issue_select
      Issue.order(name: :asc).all.map do |issue|
        [
          issue.name,
          issue.id,
        ]
      end
    end
  end
end

app/views/admin/actions/_action.html.slim
tr
  td
    = action.title
  td.text-right
    .btn-group
      = link_to 'Show', [:admin, action], class: 'btn'
      = link_to 'Edit', edit_admin_action_path(action), class: 'btn'
      = link_to 'Delete', [:admin, action], data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/admin/actions/_form.html.slim
= form_for [:admin, @action], as: :action_item do |f|
  - if @action.errors.any?
    .columns
      .column
        #flash.toast.toast-danger
          h4
            => pluralize(@action.errors.count, "error")
            | prohibited this article from being saved:
          ul
            - @action.errors.full_messages.each do |msg|
              li = msg
  .columns
    .column
      .form-group
        = f.label :issue_id, class: 'form-label'
        = f.select :issue_id, options_for_actions_issue_select, {}, { class: '' }
      .form-group
        = f.label :category_id, class: 'form-label'
        = f.select :category_id, options_for_actions_category_select, {}, { class: '' }
      .form-group
        = f.label :eyebrow, class: 'form-label'
        = f.text_field :eyebrow, class: 'form-input'
      .form-group
        = f.label :title, class: 'form-label'
        = f.text_field :title, class: 'form-input'
      .form-group
        = f.label :summary, class: 'form-label'
        = f.text_area :summary, cols: 40, rows: 2, class: 'form-input'
      .form-group
        = f.label :body, class: 'form-label'
        = f.text_area :body, cols: 40, rows: 10, class: 'form-input wysiwyg'
      .form-group
        = f.label :time_commitment, class: 'form-label'
        = f.text_field :time_commitment, class: 'form-input'
      .form-group
        = f.label :priority, class: 'form-label'
        = f.select :priority, options_for_actions_priority_select, {}, { class: '' }
      .form-group
        = f.label :event, class: 'form-switch' do
          = f.check_box :event
          i.form-icon
          | Is this action an Event?
      .form-group
        = f.label :location, class: 'form-label'
        = f.text_field :location, class: 'form-input'
      .form-group
        = f.label :happening_at, class: 'form-label'
        = f.datetime_field :happening_at, class: 'form-input'
      .form-group
        = f.label :image, class: 'form-label'
        = f.hidden_field :image, value: @action.cached_image_data
        = f.file_field :image
      - if @action.image_data? && @action.image.exists?
        label.block Current Image
        .form-group
          = image_tag(@action.image_url)
        .form-group
          => f.label :remove_image
          = f.check_box :remove_image
  .columns
    .column
      .form-group
        .btn-group
          = f.submit class: 'btn btn-primary'
          button.btn.btn-link type="reset"
            | Reset
javascript:
  $('select').selectize();

app/views/admin/actions/index.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      .columns
        .column
          - if @actions.any?
            table.table
              tbody
                = render @actions
          - else
            h3.empty
              | There are no Action Items. #{link_to 'Add one?', new_admin_action_path}
      .columns
        .column
          = link_to 'New Action', new_admin_action_path, class: 'btn btn-primary'

app/views/admin/actions/new.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      h3 New Action
      = render 'form'
      = link_to 'Back', admin_actions_path

app/views/admin/actions/show.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      - if @action.image_data? && @action.image.exists?
        = image_tag @action.image_url, class: 'img-responsive rounded'
      h1
        = @action.title
      dl
        dt Issue
        dl = @action.issue.name
        dt Category
        dl = @action.category.name
        dt Eyebrow
        dl = @action.eyebrow
        dt Title
        dl = @action.title
        dt Summary
        dl = @action.summary
        dt Body
        dl == @action.body
        dt Time Commitment
        dl = @action.time_commitment
        dt Priority
        dl = @action.priority
        dt Event
        dl = @action.event
        dt Location
        dl = @action.location
        dt Date and Time
        dl = @action.happening_at
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      .btn-group
        = link_to 'Edit', edit_admin_action_path(@action), class: 'btn'
        = link_to 'Back', admin_actions_path, class: 'btn'