config/routes.rb
Rails.application.routes.draw do
  mount ActionImageUploader::UploadEndpoint, at: '/action_images'
  mount CategoryIconUploader::UploadEndpoint, at: '/category_icons'
  mount IssueIconUploader::UploadEndpoint, at: '/issue_icons'
  mount ProfileAvatarUploader::UploadEndpoint, at: '/profile_avatars'

  namespace :admin do
    resources :actions
    resources :categories
    resources :features
    resources :issues
    resources :users

    root to: 'dashboard#index'
  end

  resource :profile, only: [:edit, :show, :update]

  root to: 'pages#home'
end

app/models/category.rb
class Category < ApplicationRecord
  include CategoryIconUploader::Attachment.new(:icon)

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    after_action :verify_authorized

    def index
      @categories = Category.all
      authorize @categories
    end

    def show
      authorize @category
    end

    def new
      @category = Category.new
      authorize @category
    end

    def edit
      authorize @category
    end

    def create
      @category = Category.new(category_params)
      authorize @category

      if @category.save
        redirect_to(
          [:admin, @category], notice: 'Category was successfully created.'
        )
      else
        render :new
      end
    end

    def update
      authorize @category
      if @category.update(category_params)
        redirect_to(
          [:admin, @category], notice: 'Category was successfully updated.'
        )
      else
        render :edit
      end
    end

    def destroy
      authorize @category
      @category.destroy
      redirect_to(
        admin_categories_url, notice: 'Category was successfully removed.'
      )
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(
        :name, :icon
      )
    end
  end
end

app/views/admin/categories/_category.html.slim
tr
  td
    - if category.icon_data? && category.icon.exists?
      span.mr-10
        = image_tag category.icon_url, size: '32x32', class: 'vertical-middle'
    = category.name
  td.text-right
    .btn-group
      = link_to 'Show', [:admin, category], class: 'btn'
      = link_to 'Edit', edit_admin_category_path(category), class: 'btn'
      = link_to 'Delete', [:admin, category], data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/admin/categories/_form.html.slim
= form_for [:admin, @category] do |f|
  - if @category.errors.any?
    .columns
      .column
        #flash.toast.toast-danger
          h4
            => pluralize(@category.errors.count, "error")
            | prohibited this article from being saved:
          ul
            - @category.errors.full_messages.each do |msg|
              li = msg

  .columns
    .column
      .form-group
        = f.label :name, class: 'form-label'
        = f.text_field :name, class: 'form-input'
  .columns
    .column.col-6
      .form-group
        = f.label :icon, class: 'form-label'
        = f.hidden_field :icon, value: @category.cached_icon_data
        = f.file_field :icon
    .column.col-6
      - if @category.icon_data? && @category.icon.exists?
        label.block Current Icon
        = image_tag(@category.icon_url, size: '32x32')

  .columns
    .column
      .form-group
        .btn-group
          = f.submit class: 'btn btn-primary'
          button.btn.btn-link type="reset"
            | Reset

app/views/admin/categories/index.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      .columns
        .column
          - if @categories.any?
            table.table
              tbody
                = render @categories
          - else
            h3.empty
              | There are no categories. #{link_to 'Add one?', new_admin_category_path}
      .columns
        .column
          = link_to 'New Category', new_admin_category_path, class: 'btn btn-primary'

app/views/admin/categories/new.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      h3 New Category
      = render 'form'
      = link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      h1
        - if @category.icon_data? && @category.icon.exists?
          span.mr-10
            = image_tag @category.icon_url, size: '64x64', class: 'text-top'
        = @category.name
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      .btn-group
        = link_to 'Edit', edit_admin_category_path(@category), class: 'btn'
        = link_to 'Back', admin_categories_path, class: 'btn'