config/routes.rb
Rails.application.routes.draw do
  mount ActionImageUploader::UploadEndpoint, at: '/action_images'
  mount CategoryIconUploader::UploadEndpoint, at: '/category_icons'
  mount IssueIconUploader::UploadEndpoint, at: '/issue_icons'
  mount ProfileAvatarUploader::UploadEndpoint, at: '/profile_avatars'

  namespace :admin do
    resources :actions
    resources :categories
    resources :features
    resources :issues
    resources :users

    root to: 'dashboard#index'
  end

  resource :profile, only: [:edit, :show, :update]

  root to: 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  enum role: [:user, :admin, :ambassador]

  has_many :issues, through: :user_issues
  has_many :user_issues

  has_one :profile, dependent: :destroy

  after_create UserCallbacks.new
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    after_action :verify_authorized

    def index
      @users = User.order(created_at: :asc).all
      authorize @users
    end

    def show
      authorize @user
    end

    def new
      @user = User.new
      authorize @user
    end

    def edit
      authorize @user
    end

    def create
      @user = User.new(user_params.except(:issue_ids))
      authorize @user

      if @user.save
        update_user_issues
        redirect_to [:admin, @user], notice: 'User was successfully created.'
      else
        render :new
      end
    end

    def update
      authorize @user
      if @user.update(user_params)
        redirect_to [:admin, @user], notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      authorize @user
      @user.destroy
      redirect_to admin_users_url, notice: 'User was successfully removed.'
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def update_user_issues
      issue_ids = user_params.fetch(:issue_ids, [])
      @user.issue_ids = issue_ids if issue_ids.any?
    end

    def user_params
      params.require(:user).permit(
        :email, :password, :role, issue_ids: []
      )
    end
  end
end

app/helpers/admin/user_helper.rb
module Admin
  module UserHelper
    def options_for_user_role_select
      User.roles.map do |role|
        [
          I18n.t(
            role.first,
            scope: 'activerecord.attributes.user.roles',
          ),
          role.first,
        ]
      end
    end
  end
end

app/views/admin/users/_form.html.slim
= form_for [:admin, @user] do |f|
  - if @user.errors.any?
    .columns
      .column
        #flash.toast.toast-danger
          h4
            => pluralize(@user.errors.count, "error")
            | prohibited this user from being saved:
          ul
            - @user.errors.full_messages.each do |msg|
              li = msg
  .columns
    .column
      .form-group
        = f.label :email, class: 'form-label'
        = f.text_field :email, class: 'form-input'
      - if @user.new_record?
        .form-group
          = f.label :password, class: 'form-label'
          = f.password_field :password, class: 'form-input'
      .form-group
        = f.label :role, class: 'form-label'
        = f.select :role, options_for_user_role_select, {}
      .form-group
        h3 Associated Issues
        .columns
          = f.collection_check_boxes(:issue_ids, Issue.order(name: :asc), :id, :name) do |cb|
            .column.col-4
              = cb.label class: 'form-checkbox', for: "user_issue_#{cb.value.underscore}" do
                = cb.check_box class: 'form-checkbox', id: "user_issue_#{cb.value.underscore}"
                i.form-icon>
                = cb.text
  .columns
    .column
      .form-group
        .btn-group
          = f.submit class: 'btn btn-primary'
          button.btn.btn-link type="reset"
            | Reset
javascript:
  $('select').selectize();

app/views/admin/users/_user.html.slim
tr
  td
    = user.email
  td.text-right
    .btn-group
      = link_to 'Show', [:admin, user], class: 'btn'
      = link_to 'Edit', edit_admin_user_path(user), class: 'btn'
      = link_to 'Delete', [:admin, user], data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/admin/users/edit.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      == render 'form'

app/views/admin/users/index.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      .columns
        .column
          - if @users.any?
            table.table
              tbody
                = render @users
          - else
            h3.empty
              | There are no users. #{link_to 'Add one?', new_admin_user_path}
      .columns
        .column
          = link_to 'New User', new_admin_user_path, class: 'btn btn-primary'

app/views/admin/users/new.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      h3 New User
      = render 'form'
      = link_to 'Back', admin_users_path

app/views/admin/users/show.html.slim
section.container.grid-960
  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      h1
        = @user.email
      dl
        dt Role
        dl = t(@user.role, scope: 'activerecord.attributes.user.roles')
        - if @user.issues.any?
          dt Associated Issues
          dl
            ul
              - @user.issues.sort_by(&:name).each do |issue|
                li = issue.name

  .columns.justify-center
    .column.col-8.col-xs-12.col-sm-10
      .btn-group
        = link_to 'Edit', edit_admin_user_path(@user), class: 'btn'
        = link_to 'Back', admin_users_path, class: 'btn'